name: "CI"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*' # This triggers the workflow for version tags (e.g., v1.0.0):
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "6.0.2"
      - name: Get swift version
        run: swift --version
      - name: Build arm64 executable
        run: swift build -c release --arch arm64 --product urigami
      - name: Build x86_64 executable
        run: swift build -c release --arch x86_64 --product urigami
      - name: Create Universal Binary
        run: |
          lipo -create \
            $(swift build -c release --arch arm64 --product urigami --show-bin-path)/urigami \
            $(swift build -c release --arch x86_64 --product urigami --show-bin-path)/urigami \
            -output ./urigami

          # Verify architectures
          lipo -info ./urigami
      - name: Compress archive
        run: tar -czf ${{ github.ref_name }}.tar.gz -C . urigami
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: urigami-archive
          path: ${{ github.ref_name }}.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: urigami-archive
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          generate_release_notes: true
          files: urigami-archive/${{ github.ref_name }}.tar.gz
