name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:   
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "6.0.0" 
      - name: Get swift version
        run: swift --version # Swift 5.1.0
      - name: Build executable for release
        run: swift build -c release --arch arm64 --arch x86_64 --product urigami
      - name: Compress archive
        run: tar -czf ${{ github.ref_name }}.tar.gz -C .build/apple/Products/Release urigami
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.ref_name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: urigami
          homebrew-tap: noahkamara/homebrew-tap
          base-branch: main
          download-url: https://github.com/noahkamara/Urigami/releases/download/${{ github.ref_name }}/${{ github.ref_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.BREW_TAP_TOKEN }}

